### ISSUE TITLE
Configurable checks

### ISSUE THREAD

**Issue by MattSturgeon** [DrOverbuild/WhosAFK#1]
It would be great if the admin could configure which checks WhosAFK should do to determin whether a player is still AFK. Sometimes it may be desirable for the `/afk` command to be the only thing that could change the player's status, other times perhaps walking should also affect it.

**Comment by DrOverbuild** [comment]
I will be adding a config, and you can turn off whether or not staying still puts player into AFK mode automatically.

I will also add a permission, if the player has permission `whosafk.autoafk`, then they will automatically go afk if no movement is detected within the configurable timeout time.

**Comment by DrOverbuild** [comment]
Fixed in commit https://github.com/DrOverbuild/WhosAFK/commit/a9fe29a46b619870fa6186ea4444c518f6560347
